name: FinalTennis
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.9.25
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==0.15.0
      - astunparse==1.6.3
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - filterpy==1.4.5
      - flatbuffers==1.12
      - fonttools==4.60.1
      - gast==0.4.0
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - graphviz==0.21
      - grpcio==1.34.1
      - h5py==3.1.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - imutils==0.5.4
      - keras==2.4.3
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.6.3
      - numpy==1.19.5
      - oauthlib==3.3.1
      - opencv-python==4.11.0.86
      - opt-einsum==3.3.0
      - packaging==25.0
      - pandas==1.4.4
      - pillow==11.3.0
      - protobuf==3.20.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydot==4.0.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scipy==1.10.1
      - six==1.15.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.5.3
      - tensorflow-estimator==2.5.0
      - termcolor==1.1.0
      - tqdm==4.67.1
      - typing-extensions==3.7.4.3
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.12.1
      - zipp==3.23.0
prefix: /home/jay/miniconda3/envs/FinalTennis
